export * from "./HeaderSection"
export * from "./IntroSection"
export * from "./FirstGallerySection"
export * from "./AboutSection"
export * from "./SecondGallerySection"
export * from "./LifeSection"
export * from "./ThirdGallerySection"
export * from "./WorkEthicSection"
