import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const areaVariable = localFont({
<<<<<<< HEAD
  src: './fonts/AreaVF.woff',
=======
  src: '../assets/fonts/AreaVF.woff',
>>>>>>> ab9b4a1 (chore: include some font for styling)
  variable: '--font-area',
  weight: '100 900',
})

const bricolageGrotesque = localFont({
<<<<<<< HEAD
  src: './fonts/BricolageGrotesque.woff',
=======
  src: '../assets/fonts/BricolageGrotesque.woff',
>>>>>>> ab9b4a1 (chore: include some font for styling)
  variable: '--font-bricolage-grotesque-48pt',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by Cyndie Lauper (Minh)',
}

/**
 * The root layout component.
 * @param {{ children: React.ReactNode }} props
 * @returns {JSX.Element} JSX Element for the root layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  /**
   * The children of the root layout.
   */
  children: React.ReactNode
}>): JSX.Element {
  return (
    <html lang="en">
      <body
        /**
         * The main element of the page.
         */
        className={`${areaVariable.variable} ${bricolageGrotesque.variable} antialiased loading`}
      >
        {children}
      </body>
    </html>
  )
}
