import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

const areaVariable = localFont({
  src: "./fonts/AreaVF.woff",
  variable: "--font-area",
  weight: "100 900",
})

const bricolageGrotesque = localFont({
  src: "./fonts/BricolageGrotesque.woff",
  variable: "--font-bricolage-grotesque-48pt",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Cyndie Lauper (Minh)",
}

/**
 * The root layout component.
 * @param {{ children: React.ReactNode }} props
 * @returns {JSX.Element} JSX Element for the root layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  /**
   * The children of the root layout.
   */
  children: React.ReactNode
}>): JSX.Element {
  return (
    <html lang="en">
      <body
        /**
         * The main element of the page.
         */
        className={`${areaVariable.variable} ${bricolageGrotesque.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
